name: Verify Commit
description: This action verifies the PR commit using Gitsign.
on: [pull_request]
jobs:
  verify:
    runs-on: ubuntu-latest
    name: Verify commit
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: gsoc2/actions/setup-gitsign@main
      - shell: bash
        run: |
          gitsign verify --certificate-identity-regexp="^.*@gsoc2.dev$" --certificate-oidc-issuer="https://accounts.google.com"
