# Copyright 2022 Gsoc2.
# SPDX-License-Identifier: Apache-2.0

name: Action Lint

on:
  pull_request:
    branches:
      - 'main'

jobs:

  action-lint:
    name: Action lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
      - id: get_yamls
        run: |
          yamls=$(find . -name "*.yaml" -iname '.gsoc2/source.yaml')
          echo "files="${yamls}"" >> $GITHUB_OUTPUT
      - uses: reviewdog/action-actionlint@v1
        with:
          actionlint_flags: ${{ steps.get_yamls.outputs.files }}
