# Copyright 2022 Gsoc2.
# SPDX-License-Identifier: Apache-2.0

name: Action Lint

on:
  pull_request:
    branches:
      - 'main'

jobs:

  action-lint:
    name: Action lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4
      - id: get_yamls
        run: |
          yamls=$(find . -name "*.yaml" -iname '.gsoc2/source.yaml')
          echo "files="${yamls}"" >> $GITHUB_OUTPUT
      - uses: reviewdog/action-actionlint@v1
        with:
          actionlint_flags: ${{ steps.get_yamls.outputs.files }}
